baseURL = 'https://frontierdigital.net'
languageCode = 'en-gb'
theme = 'frontiertheme'

enableRobotsTXT = true

disqusShortname = 'frontierdigital'

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 4

[[menu.main]]
identifier = "careers"
name = "Careers"
url = "http://22238495.hs-sites.com/careers"
weight = 2

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 3
