baseURL = 'https://frontier-digital.co.uk'
languageCode = 'en-gb'
title = 'Frontier Digital - Cloud Platform and Devops Professional Services Company'
theme = 'frontiertheme'

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/home/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 4

[[menu.main]]
identifier = "services"
name = "Services"
url = "/services/"
weight = 2

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 3
